### PR TITLE
Upgrade all the things

### LINKED ISSUE #24: [Feature request] Remove dependence on bower
Since Bower is deprecated in favor of npm/yarn, it'd be nice if this addon could put its video.js dependency into package.json instead of bower.json.

See also:

- http://emberjs.com/blog/2017/01/23/ember-2-11-released.html
- https://simplabs.com/blog/2017/02/13/npm-libs-in-ember-cli.html

### LINKED ISSUE #25: Fix breaking changes in FastBoot 1.0
The current `ember-cli-fastboot` releases (1.0.0-rc.1 and above) introduce breaking changes. These will most likely break your current FastBoot implementation.

See https://github.com/ember-fastboot/ember-cli-fastboot/issues/387 for more information and a guide on how to fix your addon. Also you may want to visit the `-fastboot` Slack channel to get help from other users.

*Note: this issue has been created automatically, by searching for certain patterns in your code. If you think this has been falsely created, feel free to close!*

### PR DESCRIPTION
**Pull request by mwisner**
This PR updates and tweaks a few things. However it's mostly focused on two major efforts:

**Upgrade all dependencies and project to latest ember version(s)**
This includes things like replacing jshint with eslint, upgrading packages used by dummy application (ember-bootstrap) and finally any "core" packages. Also dropped support for Ember 1.13.

In an effort to drop support for bower I also un-DRY'ed some of the tests. The library that was originally used for that is a bit outdated at this point and requires bower. If anyone has any recommendations to improve this I'd be happy to fix it.

**Remove inclusion of videojs and use shim library**
Doing so allows this package to focus specifically on videojs within ember. It also allows ivy-videojs to drop bower. 

This change was inspired by the relationship between:
https://github.com/stefanpenner/ember-moment
https://github.com/jasonmit/ember-cli-moment-shim

Shim Library used:
https://github.com/joshuairl/ember-cli-videojs-shim.

closes #25 
closes #24

### CODE REVIEW

**Comment by mwisner** [comment]
Sorry for the delays with this... This is now pretty solid and ready for review / consideration.

**Comment by wouterbin** [comment]
Is there any chance that this PR is going to be merged in the near future?

**Comment by mwisner** [comment]
If anyone is interested, I've also created two very light shim libraries for videojs-contrib-hls and videojs-contrib-dash

https://github.com/mwisner/ember-videojs-dash
https://github.com/mwisner/ember-videojs-hls

While not specifically tied to this addon in anyway, they do end up working for the ivy-videojs provided components.

This means #14 and #23 are both closeable.

**Comment by mwisner** [comment]
Hi @omghax,

With this PR being open for a while now, i'm just curious if you or any of the other members from IvyApp have any feedback?

I've been using this for sometime now on our product and haven't ran into any issues.

**Comment by flexyford** [comment]
Any update on this? I've also been using the forked version and it's been working great 👍

**Comment by lougreenwood** [comment]
Hi - I get this error on Ember 3.1 & Fastboot:

Could not find module `videojs` imported from `ivy-videojs/components/ivy-videojs-player`

**Comment by lougreenwood** [comment]
Any movement on this PR?

**Comment by mwisner** [comment]
Hi @lougreenwood unfortunately I am not sure when I will have time to look into fixing the issues you describe.

I am also not sure what the overall status is of this PR in terms of how the maintainers feel about it. I would prefer to hear from the maintainers regarding if this is the right direction or if another direction should be taken.

Best Regards,
Matt.

**Pull request closed without merging**
